apiVersion: apps/v1
kind: Deployment
metadata:
  name: driving
  labels:
    app: driving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driving
  template:
    metadata:
      labels:
        app: driving
    spec:
      containers:
        - name: driving
          image: 271153858532.dkr.ecr.ap-northeast-2.amazonaws.com/admin11-driving:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
